### ISSUE TITLE
Mac Pro 5,1 no wireless 

### ISSUE THREAD

**Issue by wrightmac** [helloSystem/hello#454] opened 2022-12-27 17:50 UTC
I have an old MacPro 5,1 running hello system. It is a quad-core Xeon E6 with 16GB of RAM. Hellosystem is being run off of an Intel SSD 510 Series, 120GB. 

It installed without a hitch. The only real issue is that wireless doesn’t work. The wireless is Broadcom BCM43xx 1.0 (7.77.37.31.1a9). 

I do have an Ethernet switch close by so overall networking is good for me. 

I have an old iMac with dual-core processor and 8GB RAM, it will be the next experiment.

**Comment by probonopd** [comment] 2022-12-27 19:03
Thanks for reporting, we are interested in making this work properly if possible.
Closing as a duplicate of https://github.com/helloSystem/ISO/issues/78.

**Closed by probonopd** 2022-12-27 19:03 UTC
