### ISSUE TITLE
No 'easy' way to empty Trashcan

### ISSUE THREAD

**Issue by bmentink** [helloSystem/hello#177] opened 2021-06-24 00:33 UTC
No intuitive right-click empty Trash, had to open the trash can select all contents and use the DEL key to delete ..
I presume this function is incomplete ..

**Comment by linuxkettle** [comment] 2021-06-24 00:43
There are a few things about the Trashcan that are being debated: we might move it from the dock altogether. As far as I'm aware, the dock icon falls short for these reasons:
- dragging something onto it doesn't bin it
- right-click to empty doesn't work
- It in other ways doesn't act like a folder.

I believe the likes of a URI desktop file might work.

**Comment by bmentink** [comment] 2021-06-24 01:36
Fair comment ... thought it might be in the todo basket .. :)

**Comment by probonopd** [comment] 2021-06-24 17:03
Closing as a duplicate of https://github.com/helloSystem/Filer/issues/95.

**Closed by probonopd** 2021-06-24 17:03 UTC
