### ISSUE TITLE
Add lock screen

### ISSUE THREAD

**Issue by louies0623** [helloSystem/hello#429] opened 2022-12-10 07:58 UTC
Temporary diarrhea or urinary urgency at work, and not in front of the computer, Provide users with privacy protection.

**Comment by probonopd** [comment] 2022-12-10 11:24
Duplicate of https://github.com/helloSystem/hello/issues/170.

Not part of https://dl.acm.org/doi/book/10.5555/573097.

**Closed by probonopd** 2022-12-10 11:24 UTC

**Comment by probonopd** [comment] 2022-12-11 18:04
Our system is intended to become as simple as the Mac in the 80s, and to remove all the complicated stuff.

**Comment by louies0623** [comment] 2022-12-11 23:18
Yeah...It's as easy as letting others steal information.

**Comment by probonopd** [comment] 2022-12-12 18:42
Yes. The Mac never had the concept of "accounts" well until late in System 7.

**Comment by louies0623** [comment] 2022-12-27 14:28
https://github.com/helloSystem/ISO/issues/339

**Comment by louies0623** [comment] 2022-12-28 08:41
If your mobile phone has a password lock or graphic lock or face lock, it is still not necessary for laptop users.
