### ISSUE TITLE
Default typeface

### ISSUE THREAD

**Issue by bitigchi** [helloSystem/hello#152] opened 2021-03-10 11:09 UTC
Having a good looking typeface as the default system font is important.

A good default typeface should be easily readable, its weight should be neither too thin nor too thick, and should be warmer in tones, not too sharp or round.

The default typeface should cover most of the world's currently used scripts. CJK support is imperative. Having to resort to a different system font for CJK scripts would hinder the look of the system a lot; this is true for Middle-Eastern and South-Asian scripts as well.

I believe below typefaces will be a better candidate than the current one:

- Noto Fonts: Perfect coverage, decent look, but not the best looking one out there. Default weight might be too thin (see Haiku).
- IBM Plex: Great coverage, great look, only supports Korean from CJK as far as I can see (yet).
- Ubuntu Fonts: No CJK coverage, good look, may not be ideal to use because of the brand name association.
- Adobe Source Fonts: Good coverage, especially nice CJK fonts, great look, missing complex script fonts.

Experimenting these fonts with different combinations, weights, and trying them in a multi-script environment might be useful. Trying out new typefaces may also help reveal the possible shortcomings of the font rendering engine.

**Comment by probonopd** [comment] 2021-03-10 17:36
Hello @bitigchi and thanks for your considerations.
I agree that having an excellent UI typeface is very important. Thus I have given very careful thought about it.

Thus, we have settled on one of the most popular and iconic typefaces in the world, [Helvetica](https://en.wikipedia.org/wiki/Helvetica), a font that is so classic that a feature-length [documentary film](https://en.wikipedia.org/wiki/Helvetica_(film)) was made about it.

To be precise, we are using digital version of it from [URW](https://en.wikipedia.org/wiki/URW%2B%2B) which is available under a suitable free license under the name of [Nimbus Sans](https://en.wikipedia.org/wiki/Nimbus_Sans).

According to Wikipedia,

> The family supports Western Europe, East Europe, Turkish, Baltic, and Romanian languages.

At least for Western Europe want a "real" Western European typeface (one that a designer would use for real-world objects, e.g., the information system of the New York subway), not a "surrogate" font that was created "only" for the screen and is not known from the real world. Especially we do not want any font coming from a technology company, but a font that has its roots in the design world.

For CJK, we are currently falling back to the Noto fonts (I think).

Why do you think that the typefaces you suggested would be better candidates than the current one?

**Comment by probonopd** [comment] 2021-03-11 07:37
Don't be fooled by the meaning of "[Display typeface](https://en.wikipedia.org/wiki/Display_typeface)".

I agree that the way Apple was using Helvetica Neue was far from ideal, but not because Hevetica is a bad typeface but because Apple chose a way too thin wariant of it. I think the weight we are using is much better suited.

**Comment by lillycat332** [comment] 2021-10-11 20:37
I'd like to comment on this - I have some issues with reading, and I find Helvetica a very hard font to read on screens, the glyphs aren't particularly easy on the eyes especially for something like a system font where the user is staring at it all day. Helvetica is **by no means a bad font**, but it's a very hard to read font on a screen, and works much better for settings such as signage and non-body text print because of the inconsistent spacing and closed glyphs. Apple switched from it because it was hard to read and not designed for their use case, not because it's a bad font. I think a different font would make a huge difference to accessibility and readability, which are both a pretty big part of why I chose Apple in the first place

**Comment by louies0623** [comment] 2021-10-13 10:32
I'm not sure if you know that Helvetica's font family is proprietary?  Even though it has a beautiful history, but the font is patented.
Listen to my suggestion, you have to choose other fonts that are updated and open source, because you can avoid some patent legal problems, and it has a stable community to develop, and there is room for immediate correction of errors and feedback.

**Comment by lillycat332** [comment] 2021-10-14 09:31
"It's well known" and "it has a documentary" aren't exactly the best reasons to use a font :)

**Comment by louies0623** [comment] 2021-10-16 03:28
So are you planning to fix the height error of the original font yourself?

**Comment by probonopd** [comment] 2021-10-16 08:04
Do you still see this issue somewhere?

**Comment by louies0623** [comment] 2021-10-16 08:23
Globe menu

**Comment by louies0623** [comment] 2021-11-04 19:30
![20211105_032307](https://user-images.githubusercontent.com/44593430/140406377-4997c29b-108d-4402-9842-0b2ab09dfed5.jpg)
The height of the original font is not aligned with the inter supplementary font. It is very easy to make users feel unbalanced. Please observe this.

**Comment by probonopd** [comment] 2021-11-04 20:11
You have great eyes for spotting these things. :+1

Indeed the shortcuts are 2 pixels below the text on the left hand side.
Now I'd say this is a bug _somewhere_, but where?

**Comment by louies0623** [comment] 2021-11-04 23:22
Are the text in your system and the hotkey the same font on both sides?
Because your previous screen is more comfortable than it looks.
![138583182-c696f6f6-d975-43cb-bf44-67b9e2bcda60](https://user-images.githubusercontent.com/44593430/140433597-02ac6b65-71f8-42e7-bc02-1682ef3fb138.png)

**Comment by louies0623** [comment] 2021-11-04 23:50
Then I have one more thing for you to pay attention to. Have you found that only non-European fonts can be arranged very neatly? If there is, it is because of different fonts. As mentioned earlier, the height of the old fonts is too high, which causes how to align Will be wrong
![68747470733a2f2f6d69726f2e6d656469756d2e636f6d2f6d61782f3331382f312a416f5a54747a48434b41497449654a624f6a787073412e706e67](https://user-images.githubusercontent.com/44593430/140435816-2012e15e-65da-4f0d-b4a0-7d364694c8aa.png)
.

**Comment by probonopd** [comment] 2021-11-05 07:17
Yes, this is driving me crazy but I am still not 100% sure where the bug is.

**Comment by probonopd** [comment] 2021-11-05 07:19
> And your previous screen is more comfortable than it looks.

That was an experiment using Inter for _everything_. But note that on that screenshot, the text in the menu sits too low. Nuts!

**Comment by louies0623** [comment] 2021-11-05 20:32
The words on the menu were adjusted down because the old text was too tall, so if you switch the font, it looks very low. This should be the reason.

**Comment by lillycat332** [comment] 2021-11-05 21:23
> It is probably true that readability increases and it is certainly a very professional and suitable font, but it is a "computer font", not a font known from the "real world". 

The vast majority of users, even those who are more graphics-design-inclined, will not judge the font based on whether it is known "from the real world", but rather on whether they can read it and if it looks nice. While Helvetica is a very professional and certainly well known font, it's very well documented, with there being countless articles on why you shouldn't use it in UI/body text/your CV/etc etc etc, because it isn't a great "body text" font and can be difficult to read for these situations. So I think rather than pick a font based on it's recognisability and history and such, we should pick a font based on how well it works as a UI font. Inter (and other fonts) certainly does a better job for text like in the UI, considering that's what it was designed for, and it isn't too dissimilar from Helvetica anyway, it's just a lot more open and readable. This is pretty much the exact same reason Apple moved away from Helvetica Neue, it's just not readable enough

**Comment by probonopd** [comment] 2021-11-05 21:46
Apple used a way too thin variant of Helvetica Neue, this is why it was so unreadable.
But I do have respect for Inter. At least much more than I have for DejaVu and Liberation.

**Comment by lillycat332** [comment] 2021-11-09 13:06
It's not because it was too thin for the most part (I would argue that the lighter variant used in the OSX UI is better than a heavier variant since the size of the text was generally sized well enough to compensate for it), it's because of the closed apertures and inconsistent spacing because it was never meant to be used on a display. SF Pro used in modern macOS UI is light, yet still very easy to read all day because Apple used more consistent spacing, separate version for text and UI, differentiation between lowercase l and capital I with cap height, wider apertures (c, e) and wider open tails like on t, the punctuation symbols are simpler, strokes in general are straighter and cleaner, etc.. Helvetica was just never designed with screen use in mind. This is not a failing of the font, it's just a characteristic of it's design and a consequence of when it was designed

**Comment by probonopd** [comment] 2021-11-19 17:47
Pondering the use of Luxi by by Kris Holmes and Charles Bigelow from Bigelow & Holmes Inc. The Luxi typefaces are similar to Lucida – their previous font design which was used as the user interface font in Mac OS X before Apple switched to Helvetica Neue.

Readable it is, even in small sizes:

![image](https://user-images.githubusercontent.com/2480569/142667730-3b0cec7a-40a9-4667-a82c-0affeb3d283c.png)

Their license permits free distribution but not modification which might be an issue for non-Latin script.

**Comment by louies0623** [comment] 2021-12-17 16:11
I hope you can understand the disaster of the current system, so I made this card to let you know the situation.
![hello reportcard_工作區域 1](https://user-images.githubusercontent.com/44593430/146574224-9d34a144-a47c-4de4-a5e8-53b1adb3f171.png)

**Comment by louies0623** [comment] 2022-03-30 06:51
After a few days of thinking, I think Inter should be the best choice to replace URW.Because it has to be used on the system, not to mention multiple languages and Mac keyboard key icons, we can't use a font that is defective or missing words like tabmenu's Trojitá is missing á, and only has 26 Latin letters and a simple The edge point symbol is not enough, because there will be inconsistencies when using other fonts to fill in the gaps, such as the inconsistency between the shortcut keys of tabmenu and the font of the function options.

**Comment by probonopd** [comment] 2022-03-31 18:00
Where exactly do you see the missing á? Nimbus Sans seems to have it:

![image](https://user-images.githubusercontent.com/2480569/161120217-41aa164b-065b-4f30-9f89-59420e824bcf.png)

**Comment by probonopd** [comment] 2022-12-09 22:02
Nimbus Sans is our default typeface.

**Closed by probonopd** 2022-12-09 22:02 UTC

**Comment by louies0623** [comment] 2022-12-09 22:04
Yeah, the default text is normal in Japanese.
