### ISSUE TITLE
Add rsync by default

### ISSUE THREAD

**Issue by vanessa794h** [helloSystem/hello#142] opened 2021-02-24 22:05 UTC
Hi,

it would be very helpful if rsync integrates by default so I can use it immediately in terminal.

https://github.com/WayneD/rsync

**Comment by probonopd** [comment] 2021-02-28 07:57
hello @vanessa794h 

While I understand that this would be useful, we need to manage space on the ISO very carefully. Is there a "must have" use case in which you absolutely need to have rsync and cannot use `sudo pkg install rsync`?

**Comment by vanessa794h** [comment] 2021-02-28 19:24
> Is there a "must have" use case in which you absolutely need to have rsync and cannot use `sudo pkg install rsync`?

Hi there,

yes there is a "must have" situation when I use in completely offline or in certain scenarios do not have or do not want to use internet connection. It is very convenient when such a tool is already integrated. So I can quickly transfer my files and folders to external media and can still use additional handy functions of rsync.

On macOS it is integrated by default, but it uses a very outdated version.

Is it possible to add that by default, how big would be the difference for the ISO file size?

**Comment by vanessa794h** [comment] 2021-02-28 20:47
@probonopd 

Another question, I tried with `rsync --crtimes` to preserve the creation time, but in terminal it shows that `--crtimes` is not supported.

If I do the same on macOS and rsync (via homebrew installed for current rsync version) it works without problems. Can you do the same behavior as macOS? 

FreeBSD supports preserving creation time for folders and files.

**Comment by probonopd** [comment] 2021-03-01 18:19
Strange, according to https://www.freebsd.org/cgi/man.cgi?rsync `--crtimes` should be supported. In any case, this topic is out of scope for the helloSystem project since we are just using whatever https://www.freshports.org/net/rsync is providing. So if you can reproduce a bug in `rsync` installed from a FreeBSD package, you may consider reporting it at the FreeBSD bugzilla. There are already some open:

https://bugs.freebsd.org/bugzilla/buglist.cgi?quicksearch=rsync

To see the additional size needed, boot from the Live ISO and run `sudo pkg install zsync`, it will tell you how much needs to be downloaded (including dependencies).

**Comment by Nearlytivk** [comment] 2021-05-31 01:07
@probonopd 
https://github.com/WayneD/rsync/issues/166
There is a report about this problem and it looks like a kernel problem. That is FreeBSD does not support to set btime (creation time) as you like.

macOS does not have this problem, because it supports it. See here https://github.com/Homebrew/formula-patches/blob/master/rsync/patch-crtimes.diff

Can you change the kernel for helloSystem so that it is possible to set btime like on macOS?

On macOS there is even a GUI tool for users to change btime.
- A Better Finder Attributes
https://www.publicspace.net/ABetterFinderAttributes/index.html?lang=en

**Comment by Nearlytivk** [comment] 2021-05-31 01:13
Another thing, the default file manager (Files) under helloSystem does not show creation time. macOS Finder shows it since the first version (1.0) and iOS (mobile operating system) shows it too. It would be very great if you can take another default file manager for helloSystem that is more like macOS Finder or iOS Files app.

The default file manager (Tracker) of Haiku OS shows it, but the UI design is not really for helloSystem. Do you have any idea to solve it? Is there a file manager for helloSystem that can visually and functionally perform these tasks?

**Comment by probonopd** [comment] 2021-06-01 17:17
For now, rsync will not be added to the ISO in order to keep it small.

I have opened https://github.com/helloSystem/Filer/issues/94 regarding the btime feature request in Filer.

**Closed by probonopd** 2021-06-01 17:17 UTC
