### ISSUE TITLE
Ability to encrypt the system during installation 

### ISSUE THREAD

**Issue by 4knm2ps3n52lpnkw** [helloSystem/hello#492] opened 2023-03-18 16:34 UTC
There is currently (0.8.2_0H331) no way to encrypt the system during installation even though ZFS supports encryption

**Comment by probonopd** [comment] 2023-03-18 17:09
Closing as a duplicate of
* https://github.com/helloSystem/ISO/issues/15

**Closed by probonopd** 2023-03-18 17:09 UTC
