### ISSUE TITLE
Ability to install the system alongside other ones on the same drive (dualboot)

### ISSUE THREAD

**Issue by 4knm2ps3n52lpnkw** [helloSystem/hello#493] opened 2023-03-18 16:37 UTC
Currently (0.8.2_0H331) you can only install the system to the whole drive, at least from the GUI

**Comment by probonopd** [comment] 2023-03-18 17:08
Closing as a duplicate of:

* https://github.com/helloSystem/ISO/issues/140

Related:

* https://github.com/helloSystem/Utilities/issues/147

**Closed** 2023-03-18 17:08 UTC
